name: rust

on:
  release:
    types: [published]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y musl-tools
    - name: rustup
      run: rustup target add x86_64-unknown-linux-musl
    - name: build
      run: |
        cargo build --verbose --release --target x86_64-unknown-linux-musl
        cp target/x86_64-unknown-linux-musl/release/neu neu-x86_64-linux
        xz neu-x86_64-linux
    - uses: softprops/action-gh-release@v0.1.7
      with:
        name: nightly
        prerelease: true
        files: neu-x86_64-linux.xz
