name: rust

on:
  push:
    branches: [ master ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y musl-tools
    - name: rustup
      run: rustup target add x86_64-unknown-linux-musl
    - name: build
      run: |
        cargo build --verbose --release --target x86_64-unknown-linux-musl
        cp target/x86_64-unknown-linux-musl/release/neu neu-x86_64-linux
        xz neu-x86_64-linux
    - name: test
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: neu-x86_64-linux.xz
        path: neu-x86_64-linux.xz
